// Styles object for all components
export const styles = {
  header: { position: "fixed", top: 0, width: "100%", backgroundColor: "rgba(245, 241, 235, 0.95)", backdropFilter: "blur(24px)", zIndex: 1000, borderBottom: "1px solid rgba(44, 24, 16, 0.08)" },
  nav: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 48px", maxWidth: "1280px", margin: "0 auto" },
  logoSection: { display: "flex", alignItems: "center", gap: "12px" },
  logoSvg: { display: "block" },
  logo: { color: "#2C1810", fontWeight: 400, fontSize: "1.25rem", fontFamily: "Georgia, serif", margin: 0, letterSpacing: "0.5px" },
  navCenter: { display: "flex", alignItems: "center", gap: "36px" },
  navLink: { color: "#2C1810", textDecoration: "none", fontWeight: 400, fontSize: "0.95rem", fontFamily: "system-ui, sans-serif", letterSpacing: "0.3px", opacity: 0.8 },
  navRight: { display: "flex", alignItems: "center" },
  authButtons: { display: "flex", alignItems: "center", gap: "12px" },
  signInBtn: { backgroundColor: "transparent", color: "#2C1810", border: "1px solid rgba(44, 24, 16, 0.25)", padding: "12px 22px", borderRadius: 0, fontWeight: 400, cursor: "pointer", fontFamily: "system-ui, sans-serif", fontSize: "0.95rem", letterSpacing: "0.3px" },
  joinBtn: { backgroundColor: "#2C1810", color: "#F5F1EB", border: "1px solid #2C1810", padding: "12px 22px", borderRadius: 0, fontWeight: 400, cursor: "pointer", fontFamily: "system-ui, sans-serif", fontSize: "0.95rem", letterSpacing: "0.3px" },
  userSection: { display: "flex", alignItems: "center", gap: "12px", padding: "6px 12px", border: "1px solid rgba(44, 24, 16, 0.1)", backgroundColor: "rgba(44, 24, 16, 0.02)" },
  userAvatar: { width: "32px", height: "32px", overflow: "hidden", borderRadius: "2px" },
  avatarImage: { width: "100%", height: "100%", objectFit: "cover" },
  avatarPlaceholder: { width: "32px", height: "32px", backgroundColor: "#2C1810", color: "#F5F1EB", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 400, fontSize: "0.9rem", fontFamily: "system-ui, sans-serif" },
  userName: { fontSize: "0.9rem", color: "#2C1810", fontWeight: 400, fontFamily: "system-ui, sans-serif", letterSpacing: "0.3px" },
  logoutBtn: { backgroundColor: "transparent", color: "#2C1810", border: "none", padding: "4px 0", fontWeight: 400, cursor: "pointer", fontFamily: "system-ui, sans-serif", fontSize: "0.85rem", textDecoration: "underline", opacity: 0.7 },

  errorBanner: { position: "fixed", top: "88px", left: "50%", transform: "translateX(-50%)", backgroundColor: "#F5F1EB", border: "1px solid #2C1810", padding: "12px 16px", zIndex: 1100, display: "flex", alignItems: "center", gap: "12px" },
  errorText: { color: "#2C1810", fontSize: "0.9rem", margin: 0, fontFamily: "system-ui, sans-serif", fontWeight: 400 },
  errorClose: { background: "none", border: "none", color: "#2C1810", fontSize: "1.1rem", cursor: "pointer", fontWeight: 400 },

  hero: { minHeight: "100vh", backgroundColor: "#0F0A0A", display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center", position: "relative", padding: "120px 20px 80px" },
  heroBgWrap: { position: "absolute", inset: 0 },
  radialGlow: { position: "absolute", left: "50%", top: "44%", width: "80vmin", height: "80vmin", transform: "translate(-50%, -50%)", borderRadius: "50%", background: "radial-gradient(closest-side, rgba(255,153,153,0.35), rgba(255,153,153,0) 60%)", mixBlendMode: "screen" },
  lineArtWrap: { position: "relative", zIndex: 1, maxWidth: 1100, margin: "0 auto", paddingTop: "18vh" },
  heroContent: { maxWidth: "940px", position: "relative", zIndex: 2 },
  heroTitle: { fontSize: "3.6rem", fontWeight: 300, marginBottom: "16px", fontFamily: "Georgia, serif", lineHeight: 1.1, color: "#F5F1EB", letterSpacing: "1px" },
  heroTitleAccent: { fontWeight: 400, color: "#FFD2AA" },
  heroSubtitle: { fontSize: "1.15rem", marginBottom: "28px", lineHeight: 1.7, fontFamily: "system-ui, sans-serif", color: "#F5F1EB", opacity: 0.9, maxWidth: "720px", marginInline: "auto" },
  heroButtons: { display: "flex", gap: "16px", justifyContent: "center", flexWrap: "wrap" },
  lotusLayer: { position: "absolute", inset: 0, pointerEvents: "none" },
  lotus: { position: "absolute", width: 12, height: 12, borderRadius: "50%", background: "radial-gradient(circle at 30% 30%, #FFE7E7, #F6B2B2)", boxShadow: "0 0 12px rgba(255, 200, 200, 0.6)" },

  primaryBtn: { backgroundColor: "#2C1810", color: "#F5F1EB", padding: "16px 32px", fontSize: "1rem", fontWeight: 400, border: "1px solid #2C1810", borderRadius: 0, cursor: "pointer", fontFamily: "system-ui, sans-serif", letterSpacing: "0.5px" },
  secondaryBtn: { backgroundColor: "transparent", color: "#F5F1EB", padding: "16px 32px", fontSize: "1rem", fontWeight: 400, border: "1px solid rgba(245, 241, 235, 0.3)", borderRadius: 0, cursor: "pointer", fontFamily: "system-ui, sans-serif", letterSpacing: "0.5px" },

  statsSection: { padding: "100px 20px", backgroundColor: "#F5F1EB", borderTop: "1px solid rgba(44, 24, 16, 0.08)" },
  statsContainer: { maxWidth: "1100px", margin: "0 auto" },
  statGroup: { display: "flex", justifyContent: "center", alignItems: "center", gap: "64px", flexWrap: "wrap" },
  stat: { textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px" },
  statIcon: { marginBottom: "6px" },
  statNumber: { fontSize: "2.25rem", fontWeight: 300, color: "#2C1810", fontFamily: "Georgia, serif" },
  statLabel: { fontSize: "0.9rem", color: "#2C1810", fontWeight: 400, fontFamily: "system-ui, sans-serif", letterSpacing: "0.5px", opacity: 0.7 },
  statDivider: { width: "1px", height: "64px", backgroundColor: "rgba(44, 24, 16, 0.15)" },

  aboutSection: { padding: "120px 20px", backgroundColor: "#F5F1EB", borderTop: "1px solid rgba(44, 24, 16, 0.08)" },
  aboutContent: { maxWidth: "1200px", margin: "0 auto", display: "flex", alignItems: "center", gap: "72px", flexWrap: "wrap" },
  aboutLeft: { flex: 1, minWidth: "300px", display: "flex", justifyContent: "center" },
  heritageArt: { padding: "24px" },
  aboutSvg: { display: "block" },
  aboutRight: { flex: 1, minWidth: "380px" },
  sectionTitle: { fontSize: "2.6rem", fontWeight: 300, color: "#2C1810", marginBottom: "18px", fontFamily: "Georgia, serif", letterSpacing: "1px", lineHeight: 1.2 },
  aboutDesc: { fontSize: "1.05rem", lineHeight: 1.7, color: "#2C1810", marginBottom: "28px", fontFamily: "system-ui, sans-serif", fontWeight: 300, opacity: 0.85 },
  featuresList: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "18px" },
  feature: { display: "flex", alignItems: "center", gap: "12px", padding: "10px 0" },
  featureIcon: { width: "30px", height: "30px", border: "1px solid rgba(44, 24, 16, 0.2)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "0.9rem", fontWeight: 400, color: "#2C1810", fontFamily: "system-ui, sans-serif" },

  featuresSection: { padding: "120px 20px", backgroundColor: "#F5F1EB", borderTop: "1px solid rgba(44, 24, 16, 0.08)" },
  featuresContainer: { maxWidth: "1200px", margin: "0 auto", textAlign: "center" },
  featuresGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "32px", marginTop: "56px" },
  featureCard: { backgroundColor: "transparent", padding: "28px 20px", border: "1px solid rgba(44, 24, 16, 0.12)", textAlign: "center", transition: "transform 0.2s ease" },
  featureCardIcon: { fontSize: "2.2rem", marginBottom: "12px", display: "block" },
  featureTitle: { fontSize: "1.15rem", fontWeight: 400, color: "#2C1810", marginBottom: "8px", fontFamily: "Georgia, serif", letterSpacing: "0.3px" },
  featureDesc: { fontSize: "0.95rem", lineHeight: 1.6, color: "#2C1810", fontFamily: "system-ui, sans-serif", fontWeight: 300, opacity: 0.85 },

  // AI section
  aiSection: { padding: "120px 20px", backgroundColor: "#F5F1EB", borderTop: "1px solid rgba(44, 24, 16, 0.08)" },
  aiWrap: { maxWidth: "900px", margin: "0 auto" },
  aiHint: { fontSize: "1.02rem", color: "#2C1810", opacity: 0.8, marginBottom: 16 },
  aiForm: { background: "rgba(44,24,16,0.03)", border: "1px solid rgba(44,24,16,0.12)", padding: 16 },
  aiLabel: { display: "block", color: "#2C1810", fontSize: ".92rem", marginBottom: 6 },
  aiTextarea: { width: "100%", resize: "vertical", padding: 12, fontSize: "1rem", border: "1px solid rgba(44,24,16,0.2)", background: "#fff", color: "#2C1810", outline: "none" },
  aiError: { marginTop: 12, color: "#8B0000", fontSize: ".95rem" },
  aiList: { marginTop: 18, paddingLeft: 18, display: "grid", gap: 10 },
  aiItem: { listStyle: "disc", color: "#2C1810", fontSize: "1rem" },

  roleSection: { padding: "120px 20px", backgroundColor: "#F5F1EB", textAlign: "center", borderTop: "1px solid rgba(44, 24, 16, 0.08)" },
  roleHeader: { marginBottom: "56px" },
  roleSubtitle: { fontSize: "1rem", color: "#2C1810", marginTop: "10px", fontFamily: "system-ui, sans-serif", fontWeight: 300, opacity: 0.7 },
  roleCards: { display: "flex", gap: "32px", justifyContent: "center", flexWrap: "wrap", maxWidth: "900px", margin: "0 auto 48px" },
  roleCard: { backgroundColor: "transparent", border: "1px solid rgba(44, 24, 16, 0.15)", minWidth: "300px", cursor: "pointer", transition: "all 0.2s ease", position: "relative", overflow: "hidden" },
  roleCardSelected: { backgroundColor: "rgba(44, 24, 16, 0.03)", border: "1px solid #2C1810" },
  roleCardContent: { padding: "36px 24px" },
  roleTitle: { fontSize: "1.3rem", fontWeight: 400, color: "#2C1810", marginBottom: "6px", fontFamily: "Georgia, serif", letterSpacing: "0.3px" },
  roleSubtitleText: { fontSize: "0.9rem", color: "#8B4513", opacity: 0.85, marginBottom: "12px" },
  roleDesc: { fontSize: "0.98rem", lineHeight: 1.6, color: "#2C1810", fontFamily: "system-ui, sans-serif", fontWeight: 300, opacity: 0.85 },
  roleIndicator: { position: "absolute", bottom: 0, left: 0, width: "100%", height: "3px", backgroundColor: "transparent" },
  roleSelected: { width: "100%", height: "100%", backgroundColor: "#2C1810" },
  continueBtn: { backgroundColor: "#2C1810", color: "#F5F1EB", padding: "16px 36px", fontSize: "1rem", fontWeight: 400, border: "1px solid #2C1810", borderRadius: 0, cursor: "pointer", fontFamily: "system-ui, sans-serif", letterSpacing: "0.5px", transition: "all 0.2s ease" },
  disabledBtn: { opacity: 0.4, cursor: "not-allowed" },

  footer: { backgroundColor: "#2C1810", padding: "60px 20px 80px", textAlign: "center" },
  footerCrest: { maxWidth: 900, margin: "0 auto 16px" },
  footerContent: { maxWidth: "620px", margin: "0 auto" },
  footerText: { fontSize: "1rem", color: "#F5F1EB", fontFamily: "system-ui, sans-serif", fontWeight: 300 },
  footerSubtext: { fontSize: "0.85rem", color: "#F5F1EB", fontFamily: "system-ui, sans-serif", fontWeight: 300, opacity: 0.7 },

  // Loading screen
  loadingScreen: { display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", height: "100vh", backgroundColor: "#F5F1EB" },
  heritageLoader: { marginBottom: "32px" },
  loaderSvg: { display: "block" },
  loadingText: { fontSize: "1rem", color: "#2C1810", fontFamily: "system-ui, sans-serif", fontWeight: 300, letterSpacing: "0.5px" },
};