// src/styles/styles.js

export const styles = {
  // General & Loading Styles
  loadingScreen: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    fontSize: '2rem',
    color: '#8b4513',
    backgroundColor: '#fff8f0',
  },
  spinner: {
    border: '8px solid #f3f3f3',
    borderTop: '8px solid #8b4513',
    borderRadius: '50%',
    width: '60px',
    height: '60px',
    animation: 'spin 1s linear infinite',
    marginBottom: '20px',
  },
  
  // Header & Navigation
  header: {
    position: "fixed",
    top: 0,
    width: "100%",
    backgroundColor: "rgba(255, 248, 238, 0.95)",
    backdropFilter: "blur(10px)",
    zIndex: 1000,
    borderBottom: "1px solid #e5d5c3",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 40px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  logo: {
    color: "#8b4513",
    fontWeight: "800",
    fontSize: "1.8rem",
    fontFamily: "'Merriweather', serif",
  },
  navLinks: {
    display: "flex",
    alignItems: "center",
    gap: "32px",
  },
  navLink: {
    color: "#5d4037",
    textDecoration: "none",
    fontWeight: "500",
    fontSize: "1rem",
  },
  loginBtn: {
    backgroundColor: "#8b4513",
    color: "#fff",
    padding: "10px 24px",
    borderRadius: "25px",
    border: "none",
    fontWeight: "600",
    cursor: "pointer",
  },
  logoutBtn: {
    backgroundColor: "transparent",
    color: "#8b4513",
    border: "2px solid #8b4513",
    padding: "8px 22px",
    borderRadius: "25px",
    fontWeight: "600",
    cursor: "pointer",
  },

  // Hero Section
  hero: {
    position: "relative",
    height: "100vh",
    background: "linear-gradient(135deg, #8b4513 0%, #a0522d 50%, #cd853f 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    color: "#fff",
  },
  heroOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0, 0, 0, 0.4)",
  },
  heroContent: {
    position: "relative",
    zIndex: 1,
    maxWidth: "800px",
    padding: "0 20px",
  },
  heroTitle: {
    fontSize: "4rem",
    fontWeight: "900",
    marginBottom: "24px",
    fontFamily: "'Merriweather', serif",
    lineHeight: 1.1,
  },
  heroSubtitle: {
    fontSize: "1.5rem",
    marginBottom: "40px",
    lineHeight: 1.6,
    maxWidth: "600px",
    margin: "0 auto 40px",
  },
  heroButtons: {
    display: "flex",
    gap: "20px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  primaryBtn: {
    backgroundColor: "#fff",
    color: "#8b4513",
    padding: "16px 32px",
    fontSize: "1.2rem",
    fontWeight: "700",
    border: "none",
    borderRadius: "35px",
    cursor: "pointer",
    boxShadow: "0 8px 20px rgba(0, 0, 0, 0.2)",
  },
  secondaryBtn: {
    backgroundColor: "transparent",
    color: "#fff",
    border: "2px solid #fff",
    padding: "14px 30px",
    fontSize: "1.2rem",
    fontWeight: "700",
    borderRadius: "35px",
    cursor: "pointer",
  },

  // Stats Section
  statsSection: {
    padding: "80px 20px",
    backgroundColor: "#fff8f0",
  },
  statsContainer: {
    display: "flex",
    justifyContent: "space-around",
    maxWidth: "800px",
    margin: "0 auto",
    flexWrap: "wrap",
    gap: "40px",
  },
  stat: {
    textAlign: "center",
  },
  statNumber: {
    fontSize: "3rem",
    fontWeight: "900",
    color: "#8b4513",
    marginBottom: "8px",
  },
  statLabel: {
    fontSize: "1.1rem",
    color: "#5d4037",
    fontWeight: "500",
  },

  // About Section
  aboutSection: {
    padding: "100px 20px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  aboutContent: {
    display: "flex",
    alignItems: "center",
    gap: "60px",
    flexWrap: "wrap",
  },
  aboutText: {
    flex: "1",
    minWidth: "400px",
  },
  sectionTitle: {
    fontSize: "2.8rem",
    fontWeight: "800",
    color: "#8b4513",
    marginBottom: "24px",
    fontFamily: "'Merriweather', serif",
  },
  aboutDesc: {
    fontSize: "1.2rem",
    lineHeight: 1.7,
    color: "#5d4037",
    marginBottom: "32px",
  },
  benefitsList: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  benefit: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "1.1rem",
    color: "#5d4037",
  },
  benefitIcon: {
    fontSize: "1.5rem",
  },
  aboutImage: {
    flex: "1",
    minWidth: "300px",
    display: "flex",
    justifyContent: "center",
  },
  imagePlaceholder: {
    width: "300px",
    height: "300px",
    backgroundColor: "#fff8f0",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "6rem",
    boxShadow: "0 12px 30px rgba(139, 69, 19, 0.2)",
  },

  // Features Section
  featuresSection: {
    padding: "100px 20px",
    backgroundColor: "#fff8f0",
  },
  featuresGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "40px",
    maxWidth: "1200px",
    margin: "40px auto 0",
  },
  featureCard: {
    backgroundColor: "#fff",
    padding: "40px",
    borderRadius: "20px",
    textAlign: "center",
    boxShadow: "0 8px 25px rgba(139, 69, 19, 0.1)",
    transition: "transform 0.3s ease",
  },
  featureIcon: {
    fontSize: "3.5rem",
    marginBottom: "20px",
  },
  featureTitle: {
    fontSize: "1.5rem",
    fontWeight: "700",
    color: "#8b4513",
    marginBottom: "16px",
  },
  featureDesc: {
    fontSize: "1rem",
    lineHeight: 1.6,
    color: "#5d4037",
  },

  // Role Selection
  roleSection: {
    padding: "100px 20px",
    maxWidth: "1200px",
    margin: "0 auto",
    textAlign: "center",
  },
  roleSubtitle: {
    fontSize: "1.2rem",
    color: "#5d4037",
    marginBottom: "60px",
  },
  roleCards: {
    display: "flex",
    gap: "40px",
    justifyContent: "center",
    marginBottom: "50px",
    flexWrap: "wrap",
  },
  roleCard: {
    backgroundColor: "#fff",
    padding: "40px",
    borderRadius: "20px",
    maxWidth: "400px",
    cursor: "pointer",
    boxShadow: "0 8px 25px rgba(139, 69, 19, 0.1)",
    transition: "all 0.3s ease",
    border: "3px solid transparent",
  },
  roleCardSelected: {
    border: "3px solid #8b4513",
    boxShadow: "0 12px 35px rgba(139, 69, 19, 0.3)",
    backgroundColor: "#fff8f0",
  },
  roleIcon: {
    fontSize: "4rem",
    marginBottom: "20px",
  },
  roleTitle: {
    fontSize: "1.8rem",
    fontWeight: "700",
    color: "#8b4513",
    marginBottom: "16px",
  },
  roleDesc: {
    fontSize: "1.1rem",
    lineHeight: 1.6,
    color: "#5d4037",
    marginBottom: "24px",
  },
  featureList: {
    listStyle: "none",
    padding: 0,
    textAlign: "left",
  },
  featureItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "12px",
    fontSize: "1rem",
    color: "#5d4037",
  },
  checkmark: {
    color: "#4caf50",
    fontWeight: "bold",
  },
  continueBtn: {
    backgroundColor: "#8b4513",
    color: "#fff",
    padding: "16px 40px",
    fontSize: "1.3rem",
    fontWeight: "700",
    border: "none",
    borderRadius: "35px",
    cursor: "pointer",
    boxShadow: "0 8px 20px rgba(139, 69, 19, 0.3)",
  },
  disabledBtn: {
    opacity: 0.5,
    cursor: "not-allowed",
    boxShadow: "none",
  },

  // Footer
  footer: {
    backgroundColor: "#3e2723",
    color: "#fff",
    padding: "60px 20px",
    textAlign: "center",
  },
  footerContent: {
    maxWidth: "800px",
    margin: "0 auto",
  },
  footerTitle: {
    fontSize: "1.8rem",
    fontWeight: "700",
    marginBottom: "16px",
    fontFamily: "'Merriweather', serif",
  },
  footerDesc: {
    fontSize: "1.1rem",
    color: "#bcaaa4",
  },

  // Product Card Styles
  productCard: {
    card: {
      backgroundColor: '#fff',
      borderRadius: '12px',
      boxShadow: '0 4px 15px rgba(0, 0, 0, 0.1)',
      padding: '20px',
      textAlign: 'center',
    },
    image: {
      width: '100%',
      height: 'auto',
      borderRadius: '8px',
      marginBottom: '10px',
    },
    title: {
      fontSize: '1.2rem',
      fontWeight: 'bold',
      color: '#333',
    },
    price: {
      fontSize: '1.1rem',
      color: '#8b4513',
    },
  },
  
  // Client Marketplace Styles
  marketplaceContainer: {
    maxWidth: '1200px',
    margin: '40px auto',
    padding: '0 20px',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    textAlign: 'center',
  },
  marketplaceHeading: {
    fontSize: '3rem',
    marginBottom: '15px',
    color: '#8b4513',
    fontWeight: 'bold',
  },
  marketplaceSubheading: {
    fontSize: '1.2rem',
    color: '#666',
    marginBottom: '30px',
  },
  marketplaceSearchBox: {
    width: '100%',
    maxWidth: '600px',
    padding: '12px 15px',
    fontSize: '1.1rem',
    borderRadius: '6px',
    border: '1px solid #ccc',
    marginBottom: '30px',
    boxSizing: 'border-box',
  },
  productGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '40px',
    justifyContent: 'center',
    paddingTop: '20px',
  },

  // Seller Dashboard Styles
  sellerDashboardContainer: {
    maxWidth: '900px',
    margin: '80px auto',
    padding: '0 20px',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    textAlign: 'center',
  },
  sellerDashboardHeading: {
    fontSize: '2.5rem',
    marginBottom: '10px',
    color: '#8b4513',
    fontWeight: 'bold',
  },
  sellerDashboardSubheading: {
    fontSize: '1.2rem',
    color: '#555',
    marginBottom: '25px',
  },
  button: {
    padding: '12px 25px',
    fontSize: '1rem',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  addProductForm: {
    display: 'flex',
    gap: '15px',
    marginBottom: '40px',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  formInput: {
    padding: '10px',
    fontSize: '1rem',
    border: '1px solid #ccc',
    borderRadius: '4px',
  },
  productList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    textAlign: 'left',
  },
  productItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px',
    border: '1px solid #eee',
    borderRadius: '8px',
    backgroundColor: '#fff',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
  },
  productInfo: {
    flex: 1,
  },
  productTitle: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    margin: 0,
    color: '#333',
  },
  productDetails: {
    fontSize: '0.9rem',
    color: '#777',
    margin: '5px 0 0',
  },
  productActions: {
    display: 'flex',
    gap: '10px',
  },
  editBtn: {
    backgroundColor: '#2196F3',
    color: '#fff',
    border: 'none',
    padding: '8px 12px',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  deleteBtn: {
    backgroundColor: '#f44336',
    color: '#fff',
    border: 'none',
    padding: '8px 12px',
    borderRadius: '4px',
    cursor: 'pointer',
  },
};